#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include <string>
#include <cstdlib>
#include "root_directory.h" // This is a configuration file generated by CMake.

class FileSystem
{
private:
  typedef std::string (*Builder) (const std::string& path);

public:
  static std::string getPath(const std::string& path)
  {
    return getPathBuilder()(path);
  }

  static void setRoot(const std::string& path)
  {
    getRoot() = path;
  }

private:
  static std::string & getRoot()
  {
    static std::string root = []() {
      char const * envRoot = getenv("LOGL_ROOT_PATH");
      if (envRoot != nullptr)
        return std::string(envRoot);

#ifndef __ANDROID__
      return std::string(logl_root);
#else
      return std::string("");
#endif
    }();

    return root;
  }

  //static std::string(*foo (std::string const &)) getPathBuilder()
  static Builder getPathBuilder()
  {
    if (getRoot() != "")
      return &FileSystem::getPathRelativeRoot;
    else
      return &FileSystem::getPathRelativeBinary;
  }

  static std::string getPathRelativeRoot(const std::string& path)
  {
    return getRoot() + std::string("/") + path;
  }

  static std::string getPathRelativeBinary(const std::string& path)
  {
#ifndef __ANDROID__
    return "../../../" + path;
#else
    return path;
#endif
  }
};

// FILESYSTEM_H
#endif
